### ISSUE TITLE
Slider functionality

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#1]
1. Основой хорошего приложение является его 'прочность'/стабильность - юзер ни при каких обстоятельствах не должен поломать слайдер.
Сейчас слайдер можно очень легко поломать, например выставив не валидный шаг (0, или дробный) и т.д. все подобные кейсы нужно пофиксить.
 
![image](https://user-images.githubusercontent.com/44312820/96419644-9e5ac600-121e-11eb-965a-ba29f0793a3d.png)

2. Тултип тоже должен быть интерактивным, нужно добавить возможность менять значения слайдера перетягивая тултип, также как сейчас его можно менять за 'бегунок'. Так будет гораздо удобнее с точки зрения юзабилити, т.к. не придётся целится на маленький thumb, чтобы поменять значение.

3. Также сейчас не учтено множество юзкейсов при которых слайдер работает не верно. ![image](https://user-images.githubusercontent.com/44312820/96418907-9c443780-121d-11eb-9d65-161e75564adc.png)

4. Слайдер всегда должен сохранять свои значения, даже если были поменены флаги. Сейчас если сменить слайдер с диапазонного на одиночный и обратно, то значения второго бегунка сбросятся. (при этом если при переключении слайдера на диапазон обратно значение второго бегунка будет не валидно - его нужно будет скипнуть на бизжайшее возможное по шагу)

5. При смене шага сразу должны меняться значения слайдера, в слайдере не должно оставаться невалидных значений. Слайдер должен быть масикмально отзвычивым.

6. Шаг на шкале должен быьть равеш шагу слайдера, ну или хотя бы кратным шагу, чтобы не было такого, что значение на шкале 300, а близжайшее значение которое может занять бегунок - 600.

**Comment by Nirall** [comment]
Добавил проверки шага, сделал слайдер отзывчивым при смене шага.

**Comment by Nirall** [comment]
После исправлений пока что тесты не переписывал, лишние блоки не удалял,  возможно потом пригодятся.

**Comment by Feinminen** [comment]
Бегунок и тултип могут выходить за пределы слайдера
![image](https://user-images.githubusercontent.com/44312820/98433218-8bd5fd00-20f7-11eb-94b0-b824efad252f.png)

Бегунок и тултип могут выходить за пределы значений
![image](https://user-images.githubusercontent.com/44312820/98433234-ad36e900-20f7-11eb-93fe-e179d2aaffad.png)

При неправильном выставлении шага(или любого другого инпута) - значение в инпуте не валидируется и из-за этого не понятно какое текущее значение параметра у слайдера

**Comment by Feinminen** [comment]
Сейчас можно выставить любое значение слайдера через панель, значения не валидируются:
![image](https://user-images.githubusercontent.com/44312820/99184789-0a760e80-2778-11eb-8559-984760daf9f2.png)

Также порой крайние значения почему-то не валидируются, например вот пр итаких настройках:
![image](https://user-images.githubusercontent.com/44312820/99184839-79ebfe00-2778-11eb-9cdf-e119d6a5ce1e.png)

**Comment by Feinminen** [comment]
Также порой вот такие моменты случаются
![image](https://user-images.githubusercontent.com/44312820/99184912-16ae9b80-2779-11eb-94ba-b444486d4421.png)

**Comment by Feinminen** [comment]
По прежнему валидируются не все значения с панели опций
![Peek 2020-11-30 12-26](https://user-images.githubusercontent.com/44312820/100572161-6bb8e880-3307-11eb-9b02-82555735472f.gif)

**Comment by Feinminen** [comment]
В общем явно ещё есть проблемки с выставлением стейта :)
![Peek 2020-11-30 12-31](https://user-images.githubusercontent.com/44312820/100572434-09141c80-3308-11eb-9965-d58a16578199.gif)

Также порой крайне странно выглядит фиксированное количество элементов шкалы
![image](https://user-images.githubusercontent.com/44312820/100572507-395bbb00-3308-11eb-9147-19bddde566cb.png)

Она тут не симметрична и явно напрашиваются значения в 2 и 8. Нужно сделать так, чтобы количество элементов шкалы было адаптивным - в зависимости от того сколько значений влезают в размеры слайдера :)
