### ISSUE TITLE
Fixes from the previous project

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#10]
Нужно пофиксить все недочеты, по которым я оставлял ишьюс в предыдущем проекте. Тут также должны соблюдаться все принципы БЭМ и т.д.

**Comment by Nirall** [comment]
Как лучше организовывать проверку нескольких условий? Сейчас вынесено в отдельный метод класса, может лучше выносить в отдельную функцию за пределами класса (это в Controller)?
По файловой структуре по БЭМ - например в блоке Runner используются два класса - Button, Label. Их организовывать как элементы блока Runner и помещать в папки __button и __label или т.к. это отдельные классы оставить как есть - просто вложенные папки button, label?

**Comment by Feinminen** [comment]
> Как лучше организовывать проверку нескольких условий? Сейчас вынесено в отдельный метод класса, может лучше выносить в отдельную функцию за пределами класса (это в Controller)?

В контроллер точно выносить не нужно. Тут несколько нюансов есть:
1) Не всегда проверки условий нужно делать функциями, в местах где они используются всего один раз - лучше создавать переменные, так не будет лишних функций и ничего выносить никуда не придется.
2) Если таки нужны именно функции, то тут два варианта, можно создать рядом с классом файл с хелперами и просто импортить необходимые функции или, если функций немного(одна или две), в целом, можно просто их вынести за класс.

**Comment by Feinminen** [comment]
> По файловой структуре по БЭМ - например в блоке Runner используются два класса - Button, Label. Их организовывать как элементы блока Runner и помещать в папки __button и __label или т.к. это отдельные классы оставить как есть - просто вложенные папки button, label?

Тут оставляй как есть, это нормальная файловая структура.

**Comment by Feinminen** [comment]
Сейчас вся верстка ещё не по БЭМ сделана, у тебя сейчас есть айдишники для каждого слайдера, файл стилей подключен к html, но сами стили прописаны <style> + куча повторяющегося кода для каждой панели. Я бы лучше прикурутил pug и сделал все нормально компонентно, так быстрее будет, чем пытаться сделать нормальную БЭМ структуру в обычном html.

**Comment by Feinminen** [comment]
Ещё не хватает метатегов, фавайкона и т.д.
