### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#12]
Отписывался уже в предыдущем проекте. [тык1](https://github.com/fullstack-development/front-end-best-practices/blob/16a9c99a9b176cff508f24416b4f855c31591686/JS/README.md#3.3) [тык2](https://github.com/fullstack-development/front-end-best-practices/blob/16a9c99a9b176cff508f24416b4f855c31591686/JS/README.md#1.13)

**Comment by Nirall** [comment]
Поправил, не знаю только как правильно именовать обсерверы во вьюхе. Решил обзывать наподобие пропсов-хэндлеров в Реакте - 'onClickScaleObserver'. Хотя тут скорее архитектура неудачная

**Comment by Feinminen** [comment]
> Решил обзывать наподобие пропсов-хэндлеров в Реакте - 'onClickScaleObserver'.
В целом, я думаю, норм, но порядок слов должен же быть другой onScaleClickObserver - обзервер клика на шкалу, а не обзервер шкалы кликов :)

**Comment by Feinminen** [comment]
> Поправил, не знаю только как правильно именовать обсерверы во вьюхе. Решил обзывать наподобие пропсов-хэндлеров в Реакте - 'onClickScaleObserver'. Хотя тут скорее архитектура неудачная

А зачем тебе вообще создавать обзерверы, которые ты потом прокидываешь в подклассы? Можно же в подклассах имтить событие для обзервера, а в мэйн вьюхе его отлавливать и делать все что нужно.

**Comment by Nirall** [comment]
> А зачем тебе вообще создавать обзерверы, которые ты потом прокидываешь в подклассы? Можно же в подклассах имтить событие для обзервера, а в мэйн вьюхе его отлавливать и делать все что нужно.

У меня так и сделано, тут скорее сформулировал не правильно. Подправил при рефакторинге в коммите к ишью #5, теперь есть только хэнделеры.
