### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#14]
У тебя сейчас в проекте установлен и настроен линтер, но ты же его не используешь :D

Просто если запусить линтер по всему проекту, то будет вот так:
![image](https://user-images.githubusercontent.com/44312820/101569547-42831100-3a07-11eb-87a7-88ce67fe30bc.png)

Установи расширение для IDE, поменяй команду в пэкэйдж джейосне для линтера, часть ошибок можно будет автоматически зафиксить.

**Comment by Nirall** [comment]
Не знал, что линтер можно с IDE интегрировать, так конечно удобнее ), хотел через линтер в самом конце прогонять
