### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#2]
В проекте по слайдеру должно быть явное разделение на плагин и демо страницу. Сейчас всё лежит вместе и непонятно где что :) Также в проекте можно использовать автоматический импорт, как было в прошлом проекте.
Так же тут же отпишусь, что этот проект также должен быть сделан по БЭМ: с необходимыми блоками, правильным именованием, миксинами, переиспользованиями и т.д. Сейчас из этого ничего практически нет.
main.js - явно нужно сделать js-ом, переименовать и куда-то перенести. Что такое main.js?

**Comment by Nirall** [comment]
Разбил на 2 папки - page и slider, в slider раскидал все по блокам.

**Comment by Feinminen** [comment]
Такс, возможно я мальца криво выразился, но я имел ввиду слегка другое разделение.
Это можно обсудить, но на мой взгяд более адекватное разделение на подсистеме в текущем проекте будет такое:
1) У нас есть сам плагин - slider, он основан на MVC(P) => у нас должна быть папочка относящаяся только к плагину, в которой будет в свою очередь разделение на слои. Model, View и Controller (и обсервер, т.к. по факту он является частью паттерна). Всё что относится к вьюхе самого слайдера должно лежать внутри View. У view в свою очередь должно быть разделение на шкалу, бегунок и и т.д., чтобы был принцип single responsibility и не было 'толстого' класса. При этом в корне папки plugin(или что-нибудь тип того) - будет лежать уже собранный паттерн в виде Slider.ts и там же стили для самого слайдера.
2) У нас есть дополнительная вьюха, которая нужно только для демонстрации - панель. На мой взгялд это отдельная подситема и всё что с ней связано должно соответсвтенно лежать отдельно.
3) И у нас есть demo-page, которая объединяет слайдер с панелью.

**Comment by Nirall** [comment]
Да не, вроде все логично ), единственное я не стал панель пока что отдельно выносить. Если я тебя правильно понял, ты хочешь панель сделать что-то вроде отдельного блока и на демо-странице подключать для каждого экземпляра слайдера. Но т.к. pug не используем, а через js по-моему не очень наглядно, то все панели засунул в демостраницу, отдельно только вынес скрипт инициализации. Хотя 4 раза повторять одну и ту же разметку для панелей тоже не очень. В целом, могу реализовать панель с элементами через отдельный класс, на демостранице просто подключать панели. Хотя опять же при таком варианте, демостраница без панелей по сути пустой будет.
