### ISSUE TITLE
Additional UI bugs

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#20]
При таких настройках шкала колапсится.
![image](https://user-images.githubusercontent.com/44312820/103363342-796fb280-4aed-11eb-80f1-f8bc19239690.png)

**Comment by Feinminen** [comment]
Сейчас значение слайдера может прыгнуть на невалидное на доли секунды, как будто у тебя рассинхронены опять занчения модели и вьюхи. 
![bug](https://user-images.githubusercontent.com/44312820/103363664-44179480-4aee-11eb-9636-7ca92d807e58.gif)

**Comment by Nirall** [comment]
Баги были в мастер ветке, последние измнеения пушил в дев. Ветки слил, сейчас должно быть норм
