### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#3]
Если проект реализован на TS-е, то все файлы проекта соответственно должны быть ts-ом.
![image](https://user-images.githubusercontent.com/44312820/96424723-4a071480-1225-11eb-872b-2e1a76acbe08.png)

Также лучше установить конфиг для еслинта от airbnb, так как мы по дефолту юзаем именно его.

**Comment by Nirall** [comment]
Конфиг от airbnb поставил, через него не прогонял пока что, все равно много чего переписывать буду.

**Comment by Feinminen** [comment]
Нужно всегда пытаться описывать наиболее узкую форму типов.
![image](https://user-images.githubusercontent.com/44312820/99185635-c128bd80-277d-11eb-82f9-973bd42daed6.png)
Тут комент совершенно не играет роли, в этот тип можно засунуть аболютно любое ключ-значение:
Можно просто описать точную форму объекта и сделать некоторые опции опциональными, если это необходимо.
Тут явно должен быть не Array, а tuple. Иначе это тут может быть хоть бесконечное количество элементов. Это опять же к моменту о наиболее точном описании типа.
![image](https://user-images.githubusercontent.com/44312820/99185680-03ea9580-277e-11eb-9367-e33efa7c692c.png)

**Comment by Nirall** [comment]
Добавил тип RawParamters для метода updateConfig в Контроллере. Этот тип для конфига, поступающего из панельки слайдера. Поэтому свойства minValue, maxValue, step  в нем относятся к типу 'string', когда как в типе Parameters они 'number'. Чтобы индексировались типы без ошибок, пришлось добавить в оба метода '[index: string]: string|number|boolean'. Может есть решение поэлегантнее?

**Comment by Feinminen** [comment]
Можно же просто приводить строку к числу когда мы имитим событие изменения панельки. Ну или сделать какой-нибудь каркас в котором бы все данные приходящие с панели обрабатывались и валидировались и тогда соответсвенно будет два типа - тип данных панели и тип данных приложения.
У тебя сейчас в тип можно запихнуть абсолютно любой ключ с любым примитивом.

**Comment by Nirall** [comment]
![image](https://user-images.githubusercontent.com/52122440/101812204-e0c4c300-3b3c-11eb-98e2-119064db742d.png)

У меня реализован 2-ой вариант, но вот с обработкой данных из-за типов возникают проблемы. Тип RawParameter отличается только тем что берет данные minValue, maxValue, step из формы соответственно их тип string а не number. Я их валидирую и на выходе получаю проверенное значение с типом number. Как нормально это реализовать можно? С указанием индекса в типах - [index: string]: string|number|boolean, не лучший вариант. Сейчас сделал через двойной тип string|number на RawParameters. Неужели можно реализовать только если вручную обходить все ключи или через хитрые type guard с дополнительными типами? Вроде банальная задача, но как-то сложно решается, или я что-то упускаю :)?
![image](https://user-images.githubusercontent.com/52122440/101811942-87f52a80-3b3c-11eb-9deb-75464fdda94c.png)
![image](https://user-images.githubusercontent.com/52122440/101812001-9cd1be00-3b3c-11eb-8673-3d628027f2a4.png)

**Comment by Feinminen** [comment]
> У меня реализован 2-ой вариант, но вот с обработкой данных из-за типов возникают проблемы. Тип RawParameter отличается только тем что берет данные minValue, maxValue, step из формы соответственно их тип string а не number. Я их валидирую и на выходе получаю проверенное значение с типом number. Как нормально это реализовать можно?

У тебя просто два разных типа должно быть, если я правильно понимаю в чем вопрос, первый тип - это 'сырые' данные, которые берутся с инпута, а второй тип - это тип самой модели, который собственно возвращается после валидации. Они даже по своей сути не должны быть никак связаны.

И перебор параметров можно значительно проще сделать, отпишусь в ишью по TS-у

**Comment by Nirall** [comment]
Переписал validateConfig() во Вьюхе через reduce  и spread оператор. Как быть с другими случаями использования forEach, когда надо просто обойти массив? На .map() линтер ругается, требует чтобы чего-нибудь возвращал при каждой итерации, добавлять return null как не очень кошерно, обходить через цикл for стайлгайд не рекомендует.

**Comment by Feinminen** [comment]
> Как быть с другими случаями использования forEach, когда надо просто обойти массив?

Для этих случаев как раз и существует forEach, там нет мутаций на вызываемом массиве, значит всё ок :)

**Comment by Feinminen** [comment]
Не совсем понятно что в файле с типами делают дефолтные параметры слайдера:
![image](https://user-images.githubusercontent.com/44312820/103076313-0dc6aa80-4600-11eb-9f22-71faf55abcd8.png)

**Comment by Nirall** [comment]
С validateCOnfig() там все посложнее было. Метод update использовался еще при инициализации, поэтому в validateCOnfig при инициализации попадали начальные параметры, а не только 1 параметр при обновлении, поэтому подправил еще инициалазцию Вьюх. Все еще не оптимально наверное, но в update теперь попадает только один параметр при обновлении )

**Comment by Nirall** [comment]
> Не совсем понятно что в файле с типами делают дефолтные параметры слайдера:
> ![image](https://user-images.githubusercontent.com/44312820/103076313-0dc6aa80-4600-11eb-9f22-71faf55abcd8.png)

Убрал в последнем коммите к #19
