### ISSUE TITLE
Commented code

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#4]
Нужно почистить проект от неиспользуемых кусков кода и, также, от закоменченного кода :)
![image](https://user-images.githubusercontent.com/44312820/99185001-9177b680-2779-11eb-9973-3e216fbad0ca.png)

**Comment by Feinminen** [comment]
В тестах ещё остались комменты

**Comment by Nirall** [comment]
Коммит выше, относится к issue #12
