### ISSUE TITLE
View

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#5]
Вьюху лучше разбивать на несколько компонент. Должен соблюдаться принцип единой ответственности, один класс реализует только одну функциональность.
Также сам слайдер не должен знать сколько у него каких-либо элементов.
У тебя сейчас для каждого элемента (даже если они одинаковые) - своя переменная. Для первой кнопки, для второй, для 1,2,3,4 метки и т.д. Они должны рабоатать независимо, опираясь только на какие-то входные параметры. Т.е. если вдруг у тебя будет не 4 метки, а 6, тебе нужно будет руками добавлять ещё две метки в стэйт, потом привязывать все слушатели событий и т.д. Всё это должно быть автоматизировано.

**Comment by Nirall** [comment]
Разбил Вьюху на подсистемы с учетом того, что обсуждали в телеге. Подсистему Трэк полностью изолировать не получилось. Для обработки кликов по шкале и бару требуется методы вычисления смещения и значений, которые переехали в Трэк. Можно перенести все, что на них завязано в Трэк, но тогда во основной Вьюхе останется только инициализация с подключением к html элементу

**Comment by Feinminen** [comment]
> Можно перенести все, что на них завязано в Трэк, но тогда во основной Вьюхе останется только инициализация с подключением к html элементу

В целом так и должно быть, основная вьюха должна быть ответсвенна только за объединение других вьюх, ну это имхо)

**Comment by Feinminen** [comment]
Мне кажется, что все взаимодействия между вьюхами также лучше сделать через обсервер, чтобы не было прямого влияния основной вьюхи на трэк и т.д.

Сейчас метод update - обновляет трэк, а не всю вьюху => он должен быть в трэке, имхо
Также, на мой взгляд, в основной вьюхе вообще не должно быть currentValues, т.к. получается несколько точек истиности. currentValues - данные модели и просто должны синхронизироваться с вьюхой.
И appendToNode - тоже что-то очень абстрактное и непонятное, мы опять тригерим метод трэка и добавляем что-то в какой-то узел?

**Comment by Nirall** [comment]
В коммите к #18 разделил Вьюху и Трек, убрал из Вьюхи currentValues. Убрал appendToNode  - сделал просто проброс уведомления обсервера 'AppendingToNode' до Трека. В Треке взаимодействие с компонентами по-моему лучше напрямую оставить. Просто для позиционирования элементов там куча методов вызывается, типа getWidth, getPosition, setPosition, hideLabel и т.д. Если это через обсерверы реализовывать, боюсь получится что-то громоздкое и не очень понятное.
