### ISSUE TITLE
Event observer

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#6]
Не совсем понимаю зачем нужен обсервер в контроллере, у него же нет подписок, и при инициализации он ничего не тригерит.
Также, в целом, с тем как сделан обсервер всё ок, но, имхо, т.к. по факту ты с помощью обсервера просто добавляешь дополнительный функционал для своих классов - его можно сделать абстрактным классом и просто экстенидть его там где это необходимо. (Это немного вкусовщина, поэтому это опционально, просто как предложение :))

**Comment by Nirall** [comment]
![Безымянный](https://user-images.githubusercontent.com/52122440/100541132-96e9fc00-3263-11eb-89f1-4fff504c6caa.jpg)
Через обсервер реализовано обновление значений в панельке. Можно привязать ко Вьюхе, но через контроллер показалось более правильным. Обсервер оставил как есть, просто не нравится к классам примеси делать, хотя наверно зря :).

**Comment by Feinminen** [comment]
> Через обсервер реализовано обновление значений в панельке. Можно привязать ко Вьюхе, но через контроллер показалось более правильным.

Не, все ок, к вьюхе не надо, просто не совсем очевидна связь с панелькой, особенно учитвая тот момент, что обычно привантые методы находятся внизу => можно искать только по классу где что юзается.
Сейчас открою ишью по этому поводу
