### ISSUE TITLE
Console logs

### ISSUE THREAD

**Issue by Feinminen** [Nirall/slider#8]
Консоль логи порой используются для дебага или когда проект на стадии разработки, просто чтобы что-то логировать, но для UX - они бесполезны, юзер кране маловероятно будет заглядывать в консоль разработки :)

Если хочется оставить валидацию, то можно просто сделать подсказки в UI, если что-то введено неправильно

**Comment by Nirall** [comment]
Вывод в консоль пока убрал, сообщения лучше потом прикручу, когда структура приложения устаканится :)
